name: CI/CD Pipeline for .NET 9 API on Windows 2022

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: [self-hosted, windows]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Eğer makinenizde zaten .NET 9 SDK yüklüyse bu adımı kaldırabilirsiniz.
      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test --no-build --verbosity normal

      - name: Deploy Application
        shell: powershell
        env:
          Spotify__ClientId: ${{ secrets.CLIENTID }}
          Spotify__ClientSecret: ${{ secrets.CLIENTSECRET }}
        run: |
          Write-Host "Uygulama başlatılıyor (dotnet run ile, port 5217)..."
          
          # Mevcut çalışan uygulama varsa sonlandırmak
          $existingProcess = Get-Process -Name "dotnet" -ErrorAction SilentlyContinue | Where-Object { $_.Path -like "*MyDotNet9Api.dll" }
          if ($existingProcess) {
              Write-Host "Çalışan uygulama bulundu. Sonlandırılıyor..."
              $existingProcess | ForEach-Object { $_.Kill() }
          }

          # Uygulamayı başlat
          Write-Host "Proje dizininde 'dotnet run --urls http://*:5217' komutu çalıştırılıyor..."
          Start-Process -FilePath "dotnet" -ArgumentList "run --urls http://*:5217" -NoNewWindow -WorkingDirectory $env:GITHUB_WORKSPACE
